In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X,y=load_iris(return_X_y=True)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
gnb=GaussianNB()

In [11]:
gnb.fit(X_train,y_train)

GaussianNB()

In [12]:
y_pred=gnb.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [14]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [15]:
import seaborn as sns

In [100]:
df=sns.load_dataset('tips')

In [101]:
 df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [73]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [74]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [75]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [76]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [102]:
X=df[['total_bill','tip','sex','smoker','day','size']]
y=df['time']

In [103]:
X.head()

total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [104]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [105]:
X_train.head()

total_bill   tip     sex smoker   day  size
39        31.27  5.00    Male     No   Sat     3
87        18.28  4.00    Male     No  Thur     2
169       10.63  2.00  Female    Yes   Sat     2
232       11.61  3.39    Male     No   Sat     2
144       16.43  2.30  Female     No  Thur     2

In [106]:
X_train['day'].value_counts()

day
Sat     59
Sun     53
Thur    43
Fri     15
Name: count, dtype: int64

In [107]:
from sklearn.preprocessing import LabelEncoder

In [108]:
le1=LabelEncoder()
le2=LabelEncoder()


In [109]:
import warnings
warnings.filterwarnings('ignore')
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])

In [110]:
X_train.head()

total_bill   tip  sex  smoker   day  size
39        31.27  5.00    1       0   Sat     3
87        18.28  4.00    1       0  Thur     2
169       10.63  2.00    0       1   Sat     2
232       11.61  3.39    1       0   Sat     2
144       16.43  2.30    0       0  Thur     2

In [111]:

X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])

In [112]:
X_test.head()

total_bill   tip  sex  smoker  day  size
162       16.21  2.00    0       0  Sun     3
60        20.29  3.21    1       1  Sat     2
61        13.81  2.00    1       1  Sat     2
63        18.29  3.76    1       1  Sat     4
69        15.01  2.09    1       1  Sat     2

In [113]:
## Onehot encoding-- ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [114]:

ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[4])],
                                   remainder='passthrough')


the drop='first' parameter. The drop='first' parameter means that it will drop the first category to avoid the dummy variable trap (multicollinearity).

In [115]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [116]:
X_train

array([[ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.27,  2.03,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.81,  2.34,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 12.48,  2.52,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.77,  1.47,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.69,  3.  ,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.

In [117]:
X_test

total_bill   tip  sex  smoker   day  size
162       16.21  2.00    0       0   Sun     3
60        20.29  3.21    1       1   Sat     2
61        13.81  2.00    1       1   Sat     2
63        18.29  3.76    1       1   Sat     4
69        15.01  2.09    1       1   Sat     2
..          ...   ...  ...     ...   ...   ...
142       41.19  5.00    1       0  Thur     5
32        15.06  3.00    0       0   Sat     2
242       17.82  1.75    1       0   Sat     2
7         26.88  3.12    1       0   Sun     4
243       18.78  3.00    0       0  Thur     2

[74 rows x 6 columns]

In [118]:
X_test=ct.transform(X_test)

In [119]:
X_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.

In [120]:
X_test.shape

(74, 8)

In [121]:
from sklearn.naive_bayes import GaussianNB

In [122]:
gn=GaussianNB()

In [123]:
le3=LabelEncoder()
y_train=le3.fit_transform(y_train)

In [124]:
y_test=le3.transform(y_test)

In [125]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [126]:
gn.fit(X_train,y_train)

GaussianNB()

In [127]:
y_pred=gn.predict(X_test)

In [128]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [131]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


0.9594594594594594
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        54
           1       0.87      1.00      0.93        20

    accuracy                           0.96        74
   macro avg       0.93      0.97      0.95        74
weighted avg       0.96      0.96      0.96        74

[[51  3]
 [ 0 20]]
